<a href="https://colab.research.google.com/github/oscmoral/Programacion-para-analitica-descriptiva-y-predictiva/blob/main/Practica18_Datos_duplicados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 19: Datos duplicados

Nombre: Oscar Morales Martinez

Materia: Programación para analítica descriptiva y predictiva

Carrera: Maestría en Inteligencia Artificial y Analítica de Datos

## Instrucciones:

1. Descarga el archivo dirtydata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
2. Crea un notebook en colab y guarda el archivo csv  en tu drive.
3. Agrega secciones en el colab poniendo como título el nombre de cada ejercicio

## Ejercicio 01: Duplicidad Parcial Una columna: Contar y Filtrar los registros duplicados en Duration

* Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
* Cuenta la cantidad de registros duplicados utilizando solo la información de columna Duration e imprime
* Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
* Filtra los datos y obten los registros sin duplicados

Paso 1: Importar librerias

In [1]:
import pandas as pd

Paso 2: Acceso a Google Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Paso 3: Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.

In [4]:
path = "/content/drive/MyDrive/ClassFiles/dirtydata.csv"
df = pd.read_csv(path)

df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

Paso 4: Cuenta la cantidad de registros duplicados utilizando solo la información de columna Duration e imprime

In [5]:
duplicados_duration = df.duplicated(subset=['Duration']).sum()

print("Registros duplicados en Duration:", duplicados_duration)

Registros duplicados en Duration: 28

Paso 5: Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.

In [6]:
conteo_duration = df['Duration'].value_counts()
print(conteo_duration)

Duration
60     24
45      6
450     1
30      1
Name: count, dtype: int64

Paso 6: Filtra los datos y obten los registros sin duplicados

In [7]:
df_sin_duplicados_duration = df.drop_duplicates(subset=['Duration'])
df_sin_duplicados_duration

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
3        45  '2020/12/04'    109       175     282.4
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1

## Ejercicio 02: Duplicidad Parcial Dos columnaa: Contar y Filtrar los registros duplicados en Pulse y MaxPulse

* Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
* Cuenta la cantidad de registros duplicados utilizando la información de las columnas Pulse y Maxpulse
* Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
* Filtra los datos y obten los registros cuando keep = 'last'

Paso 1: Cuenta la cantidad de registros duplicados utilizando la información de las columnas Pulse y Maxpulse

In [8]:
duplicados_pulse = df.duplicated(subset=['Pulse', 'Maxpulse']).sum()

print("Duplicados en Pulse y Maxpulse:", duplicados_pulse)

Duplicados en Pulse y Maxpulse: 3

Paso 2: Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.

In [11]:
conteo_pulse = df[['Pulse','Maxpulse']].value_counts()
print(conteo_pulse)

Pulse  Maxpulse
100    120         4
92     115         1
       118         1
97     125         1
90     112         1
98     120         1
       123         1
       124         1
100    119         1
       132         1
102    126         1
       127         1
       129         1
103    123         1
       132         1
       135         1
       147         1
104    132         1
       134         1
105    132         1
106    128         1
108    131         1
109    133         1
       175         1
110    130         1
       136         1
117    145         1
       148         1
130    101         1
Name: count, dtype: int64

Paso 3: Filtra los datos y obten los registros cuando keep = 'last'

In [12]:
df_pulse_last = df.drop_duplicates(subset=['Pulse','Maxpulse'], keep='last')
df_pulse_last

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Ejercicio 03 Duplicidad Total o Exacta: Contar y Filtrar los registros duplicados

* Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
* Cuenta la cantidad de registros duplicados exactos (todas las columnas)
* Utiliza sum() e imprime la cantidad de registros con duplicidad exacta
* Filtra los datos y obten los registros cuando keep = 'last'

Paso 1: Cuenta la cantidad de registros duplicados exactos (todas las columnas)

In [14]:
duplicados_totales = df.duplicated()

print("Duplicados en todas las columnas:", duplicados_totales)

Duplicados en todas las columnas: 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

Paso 2: Utiliza sum() e imprime la cantidad de registros con duplicidad exacta

In [15]:
duplicados_totales = df.duplicated().sum()
print("Duplicados exactos:", duplicados_totales)

Duplicados exactos: 1

Paso 3: Filtra los datos y obten los registros cuando keep = 'last'

In [16]:
df_sin_duplicados_totales = df.drop_duplicates(keep='last')
df_sin_duplicados_totales

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Ejercicio 04: Cálculo de la media con duplicados y sin duplicados

* Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.
* Calcula e imprime la media de las columnas Pulse y MaxPulse
* Identifica los valores duplicados en las columnas Pulse y MaxPulse (Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias
* Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse

Paso 1: Calcula e imprime la media de las columnas Pulse y MaxPulse

In [17]:
media_con_duplicados = df[['Pulse','Maxpulse']].mean()
print(media_con_duplicados)

Pulse       103.5
Maxpulse    128.5
dtype: float64

Paso 2: Identifica los valores duplicados en las columnas Pulse y MaxPulse (Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias

In [18]:
df_sin_dup_pulse = df.drop_duplicates(subset=['Pulse','Maxpulse'], keep='last')

Paso 3: Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse

In [19]:
media_sin_duplicados = df_sin_dup_pulse[['Pulse','Maxpulse']].mean()
print(media_sin_duplicados)

Pulse       103.862069
Maxpulse    129.379310
dtype: float64